### ISSUE TITLE
Sua badge do Alura Challenge está aqui!

### ISSUE THREAD

**Issue by LucasdeFreitasp** [thiago-muniz/AluraDev_AluraChallenge#1]
Olá, frontender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nesse primeiro Challenge de Front-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅 
. 
Abraços e te vejo nos próximos Challenges!

![Badge - Github](https://user-images.githubusercontent.com/79534537/123152597-242cb200-d43b-11eb-9909-057f727b776b.png)

**Comment by thiago-muniz** [comment]
Obrigado!
